---
title: "Lecture Notes 9/8/2022"
author: "Grace Rade"
date: "2022-09-08"
output: html_document
---
## Lecture 02

### 1.1 Terminal Window

Terminal window: engine of your computer behind the scenes!

  - Type commants, not point and click
  
### 2.1 Reading Summary

Ch. 1 Intro: 
  
  - CRAN = App Store/Google Play for R packages
 
 
Ch. 1.1 devtools package 

  - toolbox for making R packages

  
Ch. 1.2 
  
  Book Overview

### 2.2 Minimally Vibale Product/Ch. 2

Ch. 2.1 MVP


Ch. 2.2 Take out toolbox


Ch. 2.3 What will package do?


Ch. 2.4 Sneak peak of final product (source code necessary to build package)


Ch. 2.5 create_package() function (parenthesis indicates function)
  
  - builds package skeleton
  
  - file paths specify locations of files on your computer
  
    - `create_packages("")` then tabs to set the filepath
    
  - this function should pop up a **new** RStudio Project window (work here)


Ch. 2.6 Skip


Ch. 2.7 Create a function for text manipulation


Ch. 2.8 Where do I save this function?


Ch. 2.9 Test function

  - Ch. 2.9.1 Skip

Ch. 2.10 check() that your package is valid

  - check early, check often
  
Ch. 2.11 DESCRIPTION file

  - like a package's drivers license
  
  - all of the basic info on the package, required of all packages
  
Ch. 2.12 Sharing conditions
  
  - LISENCE file

Ch. 2.13 make help files

  - `document()`
  
  - makes the package user friendly
  
Ch. 2.14 check early, check often

Ch. 2.15 Install your **local** package (on *your* computer)

  - not from CRAN online
  

## In Class Exercise (ch. 1-2 Rpkg)

```{r}
library(devtools)
```

Toy Package: regexcite

  - Functions to address a specific need, in this case helpers for work with regular expressions.

  - Version control and an open development process.

    - This is completely optional in your work, but highly recommended. You’ll see how Git and GitHub help us expose all the intermediate stages of our toy package.
    
  - Access to established workflows for installation, getting help, and checking quality.

  - Documentation for individual functions via roxygen2.

  - Unit testing with testthat.

  - Documentation for the package as a whole via an executable README.Rmd.
 
 Once in new RProject 

  - .Rbuildignore lists files that we need to have around but that should not be included when building the R package from source. More in Section 4.4.1.

  - .Rproj.user, if you have it, is a directory used internally by RStudio.

  - .gitignore anticipates Git usage and ignores some standard, behind-the-scenes files created by R and RStudio. Even if you do not plan to use Git, this is harmless.

  - DESCRIPTION provides metadata about your package. We edit this shortly.

  - NAMESPACE declares the functions your package exports for external use and the external functions your package imports from other packages. At this point, it is empty, except for a comment declaring that this is a file we will not edit by hand.

  - The R/ directory is the “business end” of your package. It will soon contain .R files with function definitions.
regexcite.Rproj is the file that makes this directory an RStudio Project.  Even if you don’t use RStudio, this file is harmless. Or you can suppress its creation with create_package(..., rstudio = FALSE)
